# args to be passed to model construction
model_args: 
  n_neuron_d: [10, 10, 10] # essential
  n_neuron_e: [100, 100, 100, 100] # essential
  shell_sections: [1,1,1,1,3,3,3,5,5]
  use_resnet: true
# args to be passed to training procedure
train_args:
  n_epoch: 10000 # essential
  start_lr: 0.001
  decay_steps: 300
  decay_rate: 0.96
  weight_decay: 0.0
  display_epoch: 100
  ckpt_file: 'model.pth'
# args used to construct data loader
data_args:
  train_paths: # essential
    - 'path/to/train/data/1'
    - 'path/to/train/data/2'
  test_paths:
    - 'path/to/test/data/1'
    - 'path/to/test/data/2'
  batch_size: 64 # essential