model_args:
  hidden_sizes: [100, 100, 100] 
  output_scale: 100
  use_resnet: true
  actv_fn: mygelu
data_args: 
  batch_size: 16
  group_batch: 1
  e_name: l_e_delta
  d_name: dm_eig
  f_name: l_f_delta
  # gvx_name: grad_vx # experimental dm training
  extra_label: true
  conv_name: conv
preprocess_args:
  preshift: false 
  prescale: false
  prefit_ridge: 1e1
  prefit_trainable: false
train_args: 
  ckpt_file: model.pth
  decay_rate: 0.5
  decay_steps: 1000
  display_epoch: 100
  force_factor: 0.1
  n_epoch: 5000
  start_lr: 0.0001
train_paths:
  - data_train/* 
test_paths:
  - data_test/*
