# args to be passed to model construction
model_args: 
  layer_sizes: [108, 100, 100, 100, 1] # essential
  use_resnet: true
  actv_fn: 'softplus'
  output_scale: 100
# args to be passed to preprocessing
preprocess_args:
  prescale_clip: 1e-2
  prefit_ridge: 1e-7
  prefit_trainable: false
# args to be passed to training procedure
train_args:
  n_epoch: 10000 # essential
  start_lr: 0.0001
  decay_steps: 500
  decay_rate: 0.96
  display_epoch: 100
  ckpt_file: 'model.pth'
# args used to construct data loader
data_args:
  batch_size: 64 # essential
  group_batch: 1
  e_name: e_cc
  d_name: [dm_eig]
# path to training and testing folders
train_paths: # essential
  - 'path/to/train/data/1'
  - 'path/to/train/data/2'
test_paths:
  - 'path/to/test/data/1'
  - 'path/to/test/data/2'